### ISSUE TITLE
issue using kubectl proxy

### ISSUE THREAD

**Issue by jaxxstorm** [hjacobs/kube-resource-report#38]
Getting the following error when using `kubectl proxy`

```
INFO:kube_resource_report.report:Querying cluster localhost:8001 (http://localhost:8001/)..
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8001
ERROR:kube_resource_report.report:HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /api/v1/nodes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f9ef4bc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
```

**Comment by hjacobs** [comment]
@jaxxstorm how do you start `kubectl proxy` and how do you run `kube-resource-report`? If you start `kubectl proxy` on your local machine and run `kube-resource-report` in a Docker container, it might not work on Mac (I have a Linux machine). If this is your problem, you might try running Docker with `--net=host` and adding the option `--clusters=http://docker.for.mac.localhost:8001` IIRC.

**Comment by jaxxstorm** [comment]
will give that a try

**Comment by jaxxstorm** [comment]
For those running into the same issue. I'm running docker for mac, so the `--kubeconfig-path` option was being set to default. I used a host mount to copy my `~/.kube/config` into the docker for mac virtual machine and it worked. Example:

```
docker run -it --user=$(id -u) --net=host -v $(pwd)/output:/output -v $HOME/.kube:/kube hjacobs/kube-resource-report:0.2.1 --kubeconfig-path /kube/config.d/admin.conf /output
```
