### ISSUE TITLE
OpenShift compatible version

### ISSUE THREAD

**Issue by erikrs** [hjacobs/kube-resource-report#44]

**Comment by zdzichu** [comment]
With openshift 3.9 (openshift v3.9.0+ba7faec-1, kubernetes v1.9.1+a0ce1bc657) , usage information is 0. I guess this is related:

```python
ERROR:kube_resource_report.report:Failed to get node usage metrics
Traceback (most recent call last):
  File "/kube_resource_report/report.py", line 156, in get_node_usage
    for node_metrics in NodeMetrics.objects(cluster.client):
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 182, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 172, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 149, in execute
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8001/apis/metrics.k8s.io/v1beta1/nodes
ERROR:kube_resource_report.report:Failed to get pod usage metrics
Traceback (most recent call last):
  File "/kube_resource_report/report.py", line 176, in get_pod_usage
    for pod_metrics in PodMetrics.objects(cluster.client, namespace=pykube.all):
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 182, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 172, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/local/lib/python3.7/site-packages/pykube/query.py", line 149, in execute
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8001/apis/metrics.k8s.io/v1beta1/pods
```
