### ISSUE TITLE
Failed to query cluster x-x-0-1:443: 'host'

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-resource-report#56]
Reported via private email:
> I deployed kube-resource-report inside my Kubernetes cluster. I'm getting the error "Failed to query cluster x-x-0-1:443: 'host'". There's no other indication of what's wrong. The IP is correct for my API server. I've set up RBAC as needed, I can hit the pod via port-forwarding, but it's not able to talk to my Kubernetes server. I don't suppose you have any ideas about what might beÂ causing this? Am I misusing your app (as in it's not meant to be deployed this way)?

**Comment by hjacobs** [comment]
This looks like a Python `KeyError` exception, so definitely something to fix (at least the error handling I guess). One of the places where this could happen is when going through Ingress rules: https://github.com/hjacobs/kube-resource-report/blob/deee48b0df86f85514ce18bb2cd07231a10ac2df/kube_resource_report/report.py#L307

**Comment by hjacobs** [comment]
Seems to be the Ingress rule problem:

```
INFO:kube_resource_report.report:Querying cluster my-kube (https://my-kube.example.org)..
ERROR:kube_resource_report.report:'host'
Traceback (most recent call last):
  File "/home/hjacobs/workspace/kube-resource-report/kube_resource_report/report.py", line 377, in get_cluster_summaries
    summary = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hjacobs/workspace/kube-resource-report/kube_resource_report/report.py", line 307, in query_cluster
    ingress = [namespace, name, application, rule["host"], 0]
KeyError: 'host'
```

Ingress causing the issue:

```
apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: something.foobar
    http:
      paths:
      - backend:
          serviceName: myturn-test
          servicePort: http
  - http:
      paths:
      - backend:
          serviceName: mytest-test
          servicePort: http
